// Composition: signoff — the canned end slide auto-appended to every carousel.
// Action grid (Like/Save/Follow/Share/Subscribe) with mono treatment + a
// direct-contact card. Brand-standard, never auto-generated by the LLM.

import type { Brand } from "../brands";
import { SlideFrame, EmphasizedHeadline } from "../primitives";
import { TOKEN, FORGE_BG_INVERTED } from "../tokens";

export type SignoffAction = { verb: string; cmd: string };

export type SignoffProps = {
  brand: Brand;
  headline?: string;
  emphasize?: string;
  actions?: SignoffAction[];
  email?: string;
  contactNote?: string;
  counter?: string;
};

const DEFAULT_ACTIONS: SignoffAction[] = [
  { verb: "Like", cmd: "tap the heart if this saved you time" },
  { verb: "Save", cmd: "pin it — the stack is the point" },
  { verb: "Follow", cmd: "@prometheus.consulting · daily field notes" },
  { verb: "Share", cmd: "send to one operator who needs this" },
  { verb: "Subscribe", cmd: "prometheusconsulting.ai — written weekly" },
];

export function SignoffComposition({
  headline = "If this was useful, do one of these.",
  emphasize = "do one of these",
  actions,
  email = "josh@prometheusconsulting.ai",
  contactNote,
  counter,
}: SignoffProps) {
  const rows = actions && actions.length ? actions : DEFAULT_ACTIONS;
  return (
    <SlideFrame eyebrow="sign-off" footerCounter={counter} background={FORGE_BG_INVERTED}>
      <div style={{ display: "flex", flex: 1, flexDirection: "column", justifyContent: "center" }}>
        <EmphasizedHeadline
          text={headline}
          emphasize={emphasize}
          fontSize={64}
          weight={700}
          letterSpacing="-0.028em"
          lineHeight={1.05}
        />

        {/* Action grid */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            borderTop: `1px solid ${TOKEN.rule}`,
            marginTop: 48,
            marginBottom: 36,
          }}
        >
          {rows.map((a, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                alignItems: "baseline",
                gap: 28,
                padding: "16px 0",
                borderBottom: `1px solid ${TOKEN.rule}`,
              }}
            >
              <div
                style={{
                  display: "flex",
                  fontFamily: "JetBrains Mono, monospace",
                  fontSize: 16,
                  color: TOKEN.ember500,
                  width: 22,
                  fontWeight: 500,
                }}
              >
                ›
              </div>
              <div
                style={{
                  display: "flex",
                  fontFamily: "JetBrains Mono, monospace",
                  fontSize: 22,
                  color: TOKEN.fg100,
                  letterSpacing: "0.18em",
                  textTransform: "uppercase",
                  fontWeight: 600,
                  width: 200,
                }}
              >
                {a.verb}
              </div>
              <div
                style={{
                  display: "flex",
                  flex: 1,
                  fontSize: 22,
                  color: TOKEN.fg300,
                  lineHeight: 1.35,
                }}
              >
                {a.cmd}
              </div>
            </div>
          ))}
        </div>

        {/* Direct contact card */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 10,
            borderLeft: `2px solid ${TOKEN.ember500}`,
            paddingLeft: 24,
          }}
        >
          <div
            style={{
              display: "flex",
              fontFamily: "JetBrains Mono, monospace",
              fontSize: 16,
              color: TOKEN.ember500,
              letterSpacing: "0.22em",
              textTransform: "uppercase",
              fontWeight: 600,
            }}
          >
            // direct contact
          </div>
          <div
            style={{
              display: "flex",
              fontFamily: "JetBrains Mono, monospace",
              fontSize: 32,
              color: TOKEN.fg100,
              fontWeight: 500,
            }}
          >
            {email}
          </div>
          {contactNote ? (
            <div
              style={{
                display: "flex",
                fontSize: 18,
                color: TOKEN.fg400,
                fontFamily: "JetBrains Mono, monospace",
              }}
            >
              {contactNote}
            </div>
          ) : null}
        </div>
      </div>
    </SlideFrame>
  );
}
