// Generates supabase/migrations/0005_seed_xp_events.sql from lib/cc-state.ts.
// Run with: node --experimental-strip-types scripts/gen-xp-seed.mjs
// (Node 22+. Outputs to stdout; pipe into the migration file.)
//
// We read cc-state.ts as a text file and extract the xp_log array via a regex
// rather than importing it — that way this script has no compile deps.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const ccStatePath = path.resolve(here, "../lib/cc-state.ts");
const src = readFileSync(ccStatePath, "utf8");

const start = src.indexOf("xp_log:");
const arrStart = src.indexOf("[", start);
let depth = 0;
let i = arrStart;
let inStr = false;
let strCh = "";
for (; i < src.length; i++) {
  const c = src[i];
  if (inStr) {
    if (c === "\\") {
      i++;
      continue;
    }
    if (c === strCh) inStr = false;
    continue;
  }
  if (c === '"' || c === "'") {
    inStr = true;
    strCh = c;
    continue;
  }
  if (c === "[") depth++;
  else if (c === "]") {
    depth--;
    if (depth === 0) break;
  }
}
const arrText = src.slice(arrStart, i + 1);

// Convert TS object-literal style to JSON: keys → quoted, single-quote strings → double-quote.
// Simple-enough heuristic: the entries are { date: "...", event: "...", xp: N, type: "..." }.
const jsonish = arrText
  .replace(/([{,]\s*)(\w+)\s*:/g, '$1"$2":')
  .replace(/'([^']*)'/g, (_, s) => JSON.stringify(s))
  .replace(/,(\s*[\]}])/g, "$1");

const entries = JSON.parse(jsonish);

const lines = [];
lines.push("-- Seed: xp_events from CC_STATE.xp_log (generated by scripts/gen-xp-seed.mjs).");
lines.push("-- project_slug is resolved at insert time via the longest matching alias.");
lines.push("");
lines.push("insert into public.xp_events (project_slug, event, xp, type, occurred_at, source)");
lines.push("select");
lines.push("  (");
lines.push("    select pa.project_slug from public.project_aliases pa");
lines.push("    where position(pa.alias in lower(e->>'event')) > 0");
lines.push("    order by length(pa.alias) desc");
lines.push("    limit 1");
lines.push("  ) as project_slug,");
lines.push("  e->>'event' as event,");
lines.push("  (e->>'xp')::int as xp,");
lines.push("  e->>'type' as type,");
lines.push("  (e->>'date')::timestamptz as occurred_at,");
lines.push("  'manual' as source");
lines.push("from jsonb_array_elements($seed$");
lines.push(JSON.stringify(entries, null, 2));
lines.push("$seed$::jsonb) as e;");

const out = lines.join("\n") + "\n";
const outPath = path.resolve(here, "../supabase/migrations/0005_seed_xp_events.sql");
writeFileSync(outPath, out, "utf8");
console.error(`Wrote ${entries.length} entries to ${outPath}`);
