import { supabaseServer } from "@/lib/supabase/server";
import { InboxReview, type InboxRow } from "./InboxReview";

export const dynamic = "force-dynamic";

export default async function EmailReviewPage() {
  const sb = supabaseServer();
  const { data, error } = await sb
    .from("inbox_emails")
    .select(
      "id, fastmail_id, from_address, from_name, to_address, subject, body_preview, body_full, received_at, category, category_confidence, category_reasoning, action_taken, draft_response, fastmail_draft_id, draft_status, sent_at, discarded_at, send_error, created_at"
    )
    .order("received_at", { ascending: false, nullsFirst: false })
    .limit(150);

  if (error) {
    return (
      <>
        <div className="header fl-reveal">
          <h1>Inbox Review</h1>
          <p className="header-sub">Could not load inbox.</p>
        </div>
        <div className="main">
          <div className="card" style={{ padding: 20, color: "var(--danger)" }}>
            {error.message}
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <div className="header fl-reveal">
        <h1>Inbox Triage</h1>
        <p className="header-sub">
          Drafts auto-generated by the engine and parked in your Fastmail Drafts mailbox.
          Review here, hit Send when you&apos;re ready. Polling every 5 min.
        </p>
      </div>
      <div className="main">
        <InboxReview rows={(data ?? []) as InboxRow[]} />
      </div>
    </>
  );
}
