-- josh-hub command-center schema (P1)
-- Single-user system. RLS enabled everywhere; reads happen via Postgres views
-- behind the service-role key. P5 will add per-user policies for magic-link auth.

create extension if not exists "pgcrypto";

-- =====================================================================
-- projects: canonical entity. Joined to GitHub repo + Vercel project via slug.
-- =====================================================================
create table public.projects (
  slug text primary key,
  name text not null,
  description text,
  repo_url text,
  vercel_project_id text,
  vercel_url text,
  live_url text,
  current_status text,            -- active | built | planned | future | archived
  badge text,                     -- Active | Built | Planned | Idea
  gradient text,
  tier int,                       -- BITL tier 0-3
  soul text,                      -- BITL one-line tagline
  mode text,                      -- code | chat | cowork
  stack text[] default '{}',
  notes text,
  last_deploy_state text,         -- READY | BUILDING | ERROR | QUEUED | CANCELED
  last_deploy_at timestamptz,
  last_touched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index projects_status_idx on public.projects (current_status);
create index projects_last_touched_idx on public.projects (last_touched_at desc nulls last);

-- =====================================================================
-- project_aliases: alternative names that map to a project. Used by the
-- session ingester to detect which project a Claude Code session was about.
-- =====================================================================
create table public.project_aliases (
  alias text primary key,
  project_slug text not null references public.projects(slug) on delete cascade,
  created_at timestamptz not null default now()
);
create index project_aliases_slug_idx on public.project_aliases (project_slug);

-- =====================================================================
-- sessions: Claude Code / Cowork / chat sessions. external_id is the
-- jsonl file path so the ingester is idempotent.
-- =====================================================================
create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  external_id text unique,
  project_slug text references public.projects(slug) on delete set null,
  mode text not null,             -- code | cowork | chat
  model text,
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_min numeric,
  message_count int not null default 0,
  tokens_in bigint not null default 0,
  tokens_out bigint not null default 0,
  tokens_cache_read bigint not null default 0,
  tokens_cache_write bigint not null default 0,
  summary text,
  tool_calls jsonb,
  raw_path text,                  -- R2 key (P2)
  created_at timestamptz not null default now()
);
create index sessions_started_idx on public.sessions (started_at desc);
create index sessions_project_idx on public.sessions (project_slug, started_at desc);

-- =====================================================================
-- message_excerpts: last ~20 messages per session for context drill-down.
-- =====================================================================
create table public.message_excerpts (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  role text not null,             -- user | assistant | tool | system
  content_preview text,
  tool_name text,
  occurred_at timestamptz
);
create index message_excerpts_session_idx on public.message_excerpts (session_id, occurred_at);

-- =====================================================================
-- deployments: Vercel deploy state per commit.
-- =====================================================================
create table public.deployments (
  id uuid primary key default gen_random_uuid(),
  vercel_deployment_id text unique,
  project_slug text references public.projects(slug) on delete set null,
  state text,                     -- READY | BUILDING | ERROR | QUEUED | CANCELED | INITIALIZING
  url text,
  commit_sha text,
  branch text,
  created_at timestamptz not null,
  ready_at timestamptz,
  error_message text
);
create index deployments_project_idx on public.deployments (project_slug, created_at desc);
create index deployments_state_idx on public.deployments (state, created_at desc);

-- =====================================================================
-- commits: GitHub commit log per project.
-- =====================================================================
create table public.commits (
  sha text primary key,
  project_slug text references public.projects(slug) on delete set null,
  message text,
  author text,
  committed_at timestamptz not null,
  additions int,
  deletions int,
  url text
);
create index commits_project_idx on public.commits (project_slug, committed_at desc);

-- =====================================================================
-- xp_events: gamification log. Source can be manual or derived from
-- sessions/commits/deploys.
-- =====================================================================
create table public.xp_events (
  id bigint generated by default as identity primary key,
  project_slug text references public.projects(slug) on delete set null,
  event text not null,
  xp int not null,
  type text not null,
  occurred_at timestamptz not null,
  source text default 'manual'    -- manual | session | commit | deploy
);
create index xp_events_occurred_idx on public.xp_events (occurred_at desc);
create index xp_events_project_idx on public.xp_events (project_slug, occurred_at desc);

-- =====================================================================
-- achievements: derived state. derivation_query is the SQL that computes
-- current_value; we keep it as a text field so achievements are declarative.
-- =====================================================================
create table public.achievements (
  id text primary key,
  name text not null,
  description text not null,
  category text,                  -- commits | skills | shipping | level | streak | tokens
  unlocked_at timestamptz,
  current_value numeric default 0,
  target_value numeric not null,
  derivation_query text
);

-- =====================================================================
-- tasks: Asana mirror (P7).
-- =====================================================================
create table public.tasks (
  id text primary key,
  project_slug text references public.projects(slug) on delete set null,
  title text not null,
  status text,
  due timestamptz,
  completed_at timestamptz,
  url text,
  synced_at timestamptz not null default now()
);
create index tasks_project_idx on public.tasks (project_slug);

-- =====================================================================
-- integrations: external service connection metadata.
-- =====================================================================
create table public.integrations (
  id text primary key,
  name text not null,
  icon text,
  color text,
  description text,
  status text default 'connected',
  config jsonb,
  last_synced_at timestamptz
);

-- =====================================================================
-- activity_feed: unified view across sessions, deploys, commits, xp.
-- =====================================================================
create view public.activity_feed as
  select
    'session'::text as kind,
    started_at as occurred_at,
    project_slug,
    summary as detail,
    jsonb_build_object(
      'id', id,
      'mode', mode,
      'model', model,
      'duration_min', duration_min,
      'tokens_in', tokens_in,
      'tokens_out', tokens_out
    ) as meta
  from public.sessions
  union all
  select
    'deploy'::text as kind,
    created_at as occurred_at,
    project_slug,
    state as detail,
    jsonb_build_object(
      'id', vercel_deployment_id,
      'state', state,
      'url', url,
      'commit_sha', commit_sha
    ) as meta
  from public.deployments
  union all
  select
    'commit'::text as kind,
    committed_at as occurred_at,
    project_slug,
    message as detail,
    jsonb_build_object(
      'sha', sha,
      'author', author,
      'additions', additions,
      'deletions', deletions
    ) as meta
  from public.commits
  union all
  select
    'xp'::text as kind,
    occurred_at,
    project_slug,
    event as detail,
    jsonb_build_object(
      'xp', xp,
      'type', type,
      'source', source
    ) as meta
  from public.xp_events;

-- =====================================================================
-- updated_at touch trigger
-- =====================================================================
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

-- =====================================================================
-- RLS — lock everything down. Server reads via service-role only.
-- P5 will add per-user policies for the public client.
-- =====================================================================
alter table public.projects enable row level security;
alter table public.project_aliases enable row level security;
alter table public.sessions enable row level security;
alter table public.message_excerpts enable row level security;
alter table public.deployments enable row level security;
alter table public.commits enable row level security;
alter table public.xp_events enable row level security;
alter table public.achievements enable row level security;
alter table public.tasks enable row level security;
alter table public.integrations enable row level security;

-- No policies. service_role bypasses RLS so server components can still read/write.
-- Anon and authenticated keys will see empty result sets until P5 adds policies.
