-- Seed: projects + aliases from CC_STATE (repos + bitl + dashboard + planned)
-- Merges 4 ground-truth lists into a single canonical projects table.

insert into public.projects
  (slug, name, description, repo_url, live_url, current_status, badge, gradient, tier, soul, stack, last_touched_at)
values
  ('ctax-partner-site', 'Community Tax Partner Site',
   'Enterprise partner program SPA -- referral portal, dashboard, AI tools, gamification, CE training, and marketing kit.',
   'https://github.com/lordshua1337/ctax-partner-site', 'https://ctax-partner-site.vercel.app',
   'active', 'Active', 'linear-gradient(90deg, #D97706, #F59E0B)', 1,
   'Keep your client. Solve the problem. Earn the fee.',
   array['Vanilla JS','SPA','24 JS modules'], '2026-03-12'::timestamptz),

  ('doodleforge', 'DoodleForge',
   'AI-powered kids drawing transformer. Forge color palette, gallery lightbox, vault system, 12 art styles, Daily Guess game.',
   'https://github.com/lordshua1337/doodleforge', 'https://doodleforge.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #FF3B30, #FF6B5B)', 1,
   'Your kid made something. It deserves to be treated like real art.',
   array['Next.js','TypeScript','Stripe','Replicate','Supabase'], '2026-03-03'::timestamptz),

  ('the-well', 'The Well',
   'Spiritual teaching app. 60+ concepts, 49 passage dossiers, 9 word corrections, bookmarking, full-text search, reading progress.',
   'https://github.com/lordshua1337/the-well', 'https://the-well-eight.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #2D6A4F, #40916C)', 1,
   'You''re not broken. You never were.',
   array['Next.js','TypeScript','Claude API','Supabase'], '2026-03-03'::timestamptz),

  ('uncommon-cents', 'Uncommon Cents',
   'Financial education app. 14 domains, 132 concepts, money script quiz, 12 wealth strategies, 10 fraud defenses, AI chat advisor.',
   'https://github.com/lordshua1337/uncommon-cents', 'https://uncommon-cents.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #16A34A, #22C55E)', 1,
   'Your financial advisor probably hasn''t mentioned half of these.',
   array['Next.js','TypeScript','Supabase'], '2026-03-03'::timestamptz),

  ('stock-pilot', 'StockPilot',
   'AI stock research + portfolio builder. 85 stocks, Financial DNA assessment, market simulator, earnings calendar, archetype coaching.',
   'https://github.com/lordshua1337/stock-pilot', 'https://stock-pilot-puce.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #00C853, #69F0AE)', 1,
   'Investing is personal. Your portfolio should know who you are.',
   array['Next.js','TypeScript','Alpha Vantage','Claude API','Supabase'], '2026-03-04'::timestamptz),

  ('josh-hub', 'josh-hub Command Center',
   'Unified command center for tracking every project, session, deploy, commit, and XP event across the ecosystem.',
   'https://github.com/lordshua1337/josh-hub', 'https://josh-hub-nine.vercel.app',
   'active', 'Active', 'linear-gradient(90deg, #FBBF24, #D97706)', 2,
   'Everything I build, tracked in one place.',
   array['Next.js','TypeScript','Supabase','Vercel'], now()),

  ('ad-intelligence', 'Ad Intelligence',
   'Competitive ad spy tool. Real Meta/Google/SEMrush links, company search, competitor tracking, weekly briefs. Pick & Shovel #2.',
   'https://github.com/lordshua1337/ad-intelligence', 'https://ad-intelligence-one.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #fb923c, #ea580c)', 3,
   'Know what your competitors are spending before they know you''re watching.',
   array['Next.js','TypeScript','Supabase'], '2026-03-03'::timestamptz),

  ('cash-cow', 'Cash Cow',
   'AI product idea generator + research pipeline. 15 niches, revenue estimates, validation scoring, Claude-powered briefs.',
   'https://github.com/lordshua1337/cash-cow', 'https://cash-cow.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #a3e635, #65a30d)', 1,
   'Stop building products nobody wants. Research first, build second.',
   array['Next.js','TypeScript','Supabase','Claude API'], '2026-03-12'::timestamptz),

  ('pipeline-simulator', 'Pipeline Simulator',
   'Kanban pipeline with Monte Carlo revenue simulation. Drag-and-drop stages, probability modeling, revenue projections.',
   'https://github.com/lordshua1337/pipeline-simulator', 'https://pipeline-simulator-woad.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #d946ef, #a21caf)', 3,
   'See where things get stuck before they get stuck.',
   array['Next.js','TypeScript','dnd-kit','Supabase'], '2026-03-03'::timestamptz),

  ('image-forge', 'Image Forge',
   'Canvas-based image editor. 13 templates, brand kit, layer system, platform resize to 12 formats, export.',
   'https://github.com/lordshua1337/image-forge', 'https://image-forge-mauve.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #f59e0b, #d97706)', 2,
   'You need a social media image. Not a Canva subscription.',
   array['Next.js','TypeScript','Canvas API','Supabase'], '2026-03-03'::timestamptz),

  ('trend-sniper', 'Trend Sniper',
   'Bloomberg-style trend dashboard. 45 mock trends, heatmap/timeline/comparison views, watchlists, alerts. Absorbed into Cash Cow.',
   'https://github.com/lordshua1337/trend-sniper', null,
   'archived', 'Built', 'linear-gradient(90deg, #1e293b, #334155)', null,
   null, array['Next.js','TypeScript'], '2026-03-03'::timestamptz),

  ('oculus', 'Oculus',
   'Wealth management CRM platform. Client pipeline, scenario lab, stress testing, portfolio rebalancer, AI reports.',
   'https://github.com/lordshua1337/oculus', 'https://occulus.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #7c3aed, #a78bfa)', 2,
   'You know your clients by name. Your software should too.',
   array['Next.js','TypeScript','Supabase','Claude API'], '2026-03-04'::timestamptz),

  ('ctax-api-proxy', 'CTAX API Proxy',
   'API gateway protecting CTAX backend endpoints.',
   'https://github.com/lordshua1337/ctax-api-proxy', null,
   'built', 'Built', 'linear-gradient(90deg, #64748b, #94a3b8)', 0,
   'One proxy to protect them all.',
   array['Node','TypeScript'], '2026-03-01'::timestamptz),

  ('auth-billing-kit', 'Auth + Billing Kit',
   'Supabase Auth + Stripe subscriptions + tier gating + usage tracking. Drop into any Next.js SaaS in 30 minutes.',
   'https://github.com/lordshua1337/auth-billing-kit', null,
   'built', 'Built', 'linear-gradient(90deg, #635BFF, #0A2540)', null,
   null, array['Next.js','Supabase Auth','Stripe','TypeScript'], '2026-03-03'::timestamptz),

  ('event-bus', 'Webhook Event Bus',
   'Central pub/sub router for inter-app communication. Fan-out delivery, 3x retries, dead letter queue, typed SDK.',
   'https://github.com/lordshua1337/event-bus', null,
   'built', 'Built', 'linear-gradient(90deg, #06b6d4, #0ea5e9)', null,
   null, array['Next.js','Supabase','Inngest','TypeScript'], '2026-03-03'::timestamptz),

  ('marcom-engine', 'Marcom Engine V3',
   'Marketing OS. Mission control dashboard, connection health checker, 7 integrations, engine locking, approval queue.',
   'https://github.com/lordshua1337/marcom-engine', 'https://marcom-engine.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #ec4899, #f472b6)', 3,
   'You''re one person running marketing. You need mission control.',
   array['Next.js','TypeScript','Supabase','Inngest'], '2026-03-03'::timestamptz),

  ('partner-portal-templates', 'Partner Portal Templates',
   '6 landing page templates with full design specs, template catalog, Supabase auth integration.',
   'https://github.com/lordshua1337/partner-portal-templates',
   'https://partner-portal-templates-lordshua1337-lordshua1337s-projects.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #0ea5e9, #38bdf8)', 2,
   'Stop building landing pages from scratch.',
   array['Next.js','TypeScript','Supabase'], '2026-03-06'::timestamptz),

  ('lifeforge', 'LifeForge',
   'Life skills RPG -- personality-driven AI companion teaches real-world skills by life stage. Skill trees, XP, quests.',
   'https://github.com/lordshua1337/lifeforge', 'https://lifeforge-two.vercel.app',
   'planned', 'Planned', 'linear-gradient(90deg, #7c3aed, #a78bfa)', 3,
   'Nobody taught you how to be an adult.',
   array['Next.js','Supabase','Stripe','Inngest','Anthropic API','Replicate','Upstash Redis','Cloudflare R2','Resend'],
   '2026-03-04'::timestamptz),

  ('balanceboss', 'BalanceBoss',
   'AI bookkeeping cleanup -- upload messy financial records, get back clean categorized books ready for CPA or QuickBooks/Xero sync.',
   'https://github.com/lordshua1337/balanceboss', 'https://balanceboss.vercel.app',
   'planned', 'Planned', 'linear-gradient(90deg, #16A34A, #22C55E)', 3,
   'Your books are a mess. We fix that.',
   array['Next.js','Supabase','Stripe','Inngest','Anthropic API','Upstash Redis','Cloudflare R2','Resend'],
   '2026-03-04'::timestamptz),

  ('bashbox', 'BashBox',
   'Dev agency landing page with periodic-table integrations, contact APIs, SEO meta tags.',
   'https://github.com/lordshua1337/Bashbox', 'https://bashbox.vercel.app',
   'built', 'Built', 'linear-gradient(90deg, #0f172a, #334155)', 2,
   'Your dev agency deserves a landing page that actually converts.',
   array['Next.js','TypeScript'], '2026-03-06'::timestamptz),

  ('project-switcher', 'Project Switcher',
   'Universal hover dropdown on top-left logo -- shows all live projects for quick switching. Single drop-in script.',
   null, null,
   'planned', 'Spec Ready', 'linear-gradient(90deg, #6B7280, #9CA3AF)', null,
   null, array['Vanilla JS'], '2026-03-04'::timestamptz),

  ('headless-cms', 'Headless CMS',
   'Custom headless content management system -- API-first, multi-tenant, structured content types, media pipeline.',
   null, null,
   'future', 'Idea', 'linear-gradient(90deg, #0ea5e9, #38bdf8)', null,
   null, array['Next.js','Supabase','TypeScript'], null);

-- Project aliases for session-ingester detection
insert into public.project_aliases (alias, project_slug) values
  ('stockpilot', 'stock-pilot'),
  ('stock pilot', 'stock-pilot'),
  ('uncommon cents', 'uncommon-cents'),
  ('the well', 'the-well'),
  ('well v2', 'the-well'),
  ('scripture', 'the-well'),
  ('word correction', 'the-well'),
  ('doodle', 'doodleforge'),
  ('ctax', 'ctax-partner-site'),
  ('partner', 'ctax-partner-site'),
  ('icp', 'ctax-partner-site'),
  ('30-day', 'ctax-partner-site'),
  ('cash cow', 'cash-cow'),
  ('trend sniper', 'cash-cow'),
  ('ad intelligence', 'ad-intelligence'),
  ('pipeline simulator', 'pipeline-simulator'),
  ('image forge', 'image-forge'),
  ('marcom', 'marcom-engine'),
  ('marketing os', 'marcom-engine'),
  ('partner portal', 'partner-portal-templates'),
  ('landing page template', 'partner-portal-templates'),
  ('balance boss', 'balanceboss'),
  ('bookkeep', 'balanceboss'),
  ('life forge', 'lifeforge'),
  ('life skills', 'lifeforge'),
  ('occulus', 'oculus'),
  ('wealth management', 'oculus'),
  ('hub', 'josh-hub'),
  ('command center', 'josh-hub'),
  ('command-center', 'josh-hub');
