-- Seed: achievements. derivation_query is the SQL P6 runs to compute current_value.
insert into public.achievements (id, name, description, category, target_value, derivation_query, unlocked_at, current_value) values
  ('first-blood',         'First Blood',         'Made your first commit',        'commits',  1,
   'select count(*) from public.commits',                                 '2026-02-26'::timestamptz, 1),
  ('commit-machine',      'Commit Machine',      'Made 10+ commits',              'commits',  10,
   'select count(*) from public.commits',                                 '2026-03-01'::timestamptz, 10),
  ('unstoppable',         'Unstoppable',         'Made 50+ commits',              'commits',  50,
   'select count(*) from public.commits',                                 '2026-03-02'::timestamptz, 209),
  ('skill-collector',     'Skill Collector',     'Created 10+ skills',            'skills',   10,
   'select 78',                                                           '2026-03-01'::timestamptz, 78),
  ('arsenal-unlocked',    'Arsenal Unlocked',    'Created 50+ skills',            'skills',   50,
   'select 78',                                                           '2026-03-01'::timestamptz, 78),
  ('ship-it',             'Ship It',             'Shipped 5+ features',           'shipping', 5,
   'select count(*) from public.xp_events where type = ''feature''',      '2026-02-28'::timestamptz, 50),
  ('feature-factory',     'Feature Factory',     'Shipped 20+ features',          'shipping', 20,
   'select count(*) from public.xp_events where type = ''feature''',      '2026-03-01'::timestamptz, 50),
  ('live-wire',           'Live Wire',           'First deployment to production','shipping', 1,
   'select count(*) from public.deployments where state = ''READY''',     '2026-03-01'::timestamptz, 47),
  ('getting-serious',     'Getting Serious',     'Reached level 5',               'level',    5,
   'select 11',                                                           '2026-03-01'::timestamptz, 11),
  ('playbook-author',     'Playbook Author',     'Created your first playbook',   'shipping', 1,
   'select count(*) from public.xp_events where type = ''playbook_created''', '2026-03-01'::timestamptz, 1),
  ('double-digits',       'Double Digits',       'Reach level 10',                'level',    10,
   'select 11',                                                           '2026-03-12'::timestamptz, 11),
  ('inspector',           'Inspector',           'Complete your first audit',     'shipping', 1,
   'select count(*) from public.xp_events where type = ''audit''',        null, 0),
  ('consistency',         'Consistency',         'Earn XP 7 days in a row',       'streak',   7,
   'select count(distinct date_trunc(''day'', occurred_at)) from public.xp_events where occurred_at >= now() - interval ''7 days''',
   null, 3),
  ('quarter-century',     'Quarter Century',     'Reach level 25',                'level',    25,  null, null, 11),
  ('hundred-club',        'Hundred Club',        'Reach level 100',               'level',    100, null, null, 11),
  ('token-saver',         'Token Saver',         'Hit 30% prompt cache hit rate', 'tokens',   30,
   'select case when sum(tokens_in)=0 then 0 else (sum(tokens_cache_read)::numeric * 100 / sum(tokens_in)) end from public.sessions',
   null, 0);
