-- Seed: xp_events from CC_STATE.xp_log (generated by scripts/gen-xp-seed.mjs).
-- project_slug is resolved at insert time via the longest matching alias.

insert into public.xp_events (project_slug, event, xp, type, occurred_at, source)
select
  (
    select pa.project_slug from public.project_aliases pa
    where position(pa.alias in lower(e->>'event')) > 0
    order by length(pa.alias) desc
    limit 1
  ) as project_slug,
  e->>'event' as event,
  (e->>'xp')::int as xp,
  e->>'type' as type,
  (e->>'date')::timestamptz as occurred_at,
  'manual' as source
from jsonb_array_elements($seed$
[
  {
    "date": "2026-03-12",
    "event": "fix: Security audit -- .gitignore hardening across 7 projects",
    "xp": 30,
    "type": "audit"
  },
  {
    "date": "2026-03-12",
    "event": "config: Full upgrade session -- evolution system, memory reorg, tool inventory",
    "xp": 25,
    "type": "config"
  },
  {
    "date": "2026-03-12",
    "event": "deploy: joshuatree viewport fix deployed to Vercel",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-12",
    "event": "deploy: cash-cow viewport fix deployed to Vercel",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-12",
    "event": "fix: joshuatree -- viewport metadata for mobile scaling",
    "xp": 20,
    "type": "bugfix"
  },
  {
    "date": "2026-03-12",
    "event": "fix: cash-cow -- viewport metadata for mobile scaling",
    "xp": 20,
    "type": "bugfix"
  },
  {
    "date": "2026-03-06",
    "event": "feat: Partner Portal Templates -- expanded tax resolution from 3 to 10 educational topics",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-06",
    "event": "feat: BashBox -- brand SVG logos on hover for 72 periodic table integrations",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-06",
    "event": "feat: BashBox -- working contact/subscribe APIs, SEO meta tags, smooth scroll",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-06",
    "event": "deploy: BashBox deployed to Vercel production (bashbox.vercel.app)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-05",
    "event": "feat: CTAX marketing kit revamp -- inline ad builder, flyer/deck/thank-you builders, smart email downloads, polished SVG cards",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-05",
    "event": "feat: CTAX portal AI tools -- replaced fake demo system with real Claude API calls for all 4 embedded tools",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-05",
    "event": "fix+feat: CTAX AI quality upgrade -- expert prompts, real AI for flyer/thank-you, ICP integration, CSS bug fix, deck UX improvement",
    "xp": 55,
    "type": "feature+bugfix"
  },
  {
    "date": "2026-03-05",
    "event": "deploy: CTAX partner site pushed to Vercel (3 commits, marketing kit + AI tools)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-04",
    "event": "plan: 5 V4 plans -- Ad Intelligence, Pipeline Simulator, Image Forge, Marcom Engine, Partner Portal Templates",
    "xp": 75,
    "type": "plan"
  },
  {
    "date": "2026-03-04",
    "event": "plan: Oculus V4 -- 5-phase plan (CRM, portfolios, scenario lab, AI reports, payments)",
    "xp": 15,
    "type": "plan"
  },
  {
    "date": "2026-03-04",
    "event": "feat: BalanceBoss Phase 1 scaffold -- auth, dashboard, IRS categories, 9-table schema, V1 plan, GitHub repo",
    "xp": 100,
    "type": "project"
  },
  {
    "date": "2026-03-04",
    "event": "feat: LifeForge Phase 1 scaffold -- auth, onboarding, skill tree, Supabase schema, 3 domains/31 nodes, V1 plan, GitHub repo",
    "xp": 100,
    "type": "project"
  },
  {
    "date": "2026-03-04",
    "event": "milestone: Cash Cow V4 complete -- 32 files, 3223 insertions, Claude+Supabase full stack",
    "xp": 100,
    "type": "milestone"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Cash Cow V4 Phase 4 -- PDF export, brief customizer, enhanced CSV, cron refresh",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Cash Cow V4 Phase 3 -- Supabase auth, rate limiting, caching, watchlists, RLS",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Cash Cow V4 Phase 2 -- revenue forecasting, playbooks, variation UI, AI recs",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Cash Cow V4 Phase 1 -- Claude-powered research, API routes, progressive loading",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "milestone: StockPilot V4 complete -- dividends, benchmarks, archetype hub, portfolio tools, market intelligence (22 files, 4 phases)",
    "xp": 100,
    "type": "milestone"
  },
  {
    "date": "2026-03-04",
    "event": "deploy: StockPilot V4 to Vercel production",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-04",
    "event": "feat: StockPilot V4 Phase 4 -- daily briefing + advanced screener",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "feat: StockPilot V4 Phase 3 -- heatmap, correlation, rebalance, DNA alignment",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "feat: StockPilot V4 Phase 2 -- archetype hub, invest pages, bias nudges, evolution",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "feat: StockPilot V4 Phase 1 -- dividends, benchmarks, cron jobs, error logging",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "feat: rebuild projects page with Vercel + GitHub Pages tabs",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "milestone: V3 Full Build Execution Plan complete -- 11 projects migrated to Vercel",
    "xp": 100,
    "type": "milestone"
  },
  {
    "date": "2026-03-04",
    "event": "deploy: 8 Vercel production deploys (ad-intel, ctax-v3, stock-pilot, ppt, pipeline-sim, image-forge, the-well, uncommon-cents)",
    "xp": 320,
    "type": "deployment"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Ad Intelligence real APIs + CTAX V3 real APIs + StockPilot real APIs + Partner Portal template previews",
    "xp": 140,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "deploy: Partner Portal Templates to GitHub Pages (dark gallery)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Partner Portal Templates dark theme + 6 template gallery",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "deploy: Marcom Engine to GitHub Pages (Bloomberg Terminal)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Marcom Engine Bloomberg Terminal dark theme + mission control",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "deploy: Cash Cow V3 to GitHub Pages (black/white/green)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-04",
    "event": "feat: Cash Cow V3 black/white/green redesign + Trend Sniper pipeline",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-04",
    "event": "fix: V3 CSS 404 rebuild + CalfCard TypeScript fix",
    "xp": 40,
    "type": "bugfix"
  },
  {
    "date": "2026-03-04",
    "event": "fix: CTAX dashboard visual overhaul + quick actions + ob-wizard disable + cookie banner",
    "xp": 80,
    "type": "bugfix"
  },
  {
    "date": "2026-03-03",
    "event": "CTAX Cycle 3 Modules 4-5 -- Social Feed, Duels, Rewards, Forecast, Goal Tracker, Quarterly Review",
    "xp": 210,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "CTAX Cycle 3 Modules 1-3 -- 9 feature builds (AI Page Gen, SEO Editor, Form Builder, Campaign Builder, Repurposer, AI Writer, ICP Tracker, Smart Guide, Competitive Intel)",
    "xp": 315,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "Omni Focus sweep -- 12-repo Code Foundation + Security audit",
    "xp": 30,
    "type": "audit"
  },
  {
    "date": "2026-03-03",
    "event": "fix: stock-pilot ticker validation on /api/market",
    "xp": 20,
    "type": "bugfix"
  },
  {
    "date": "2026-03-03",
    "event": "fix: doodleforge /api/generate MIME + size validation",
    "xp": 20,
    "type": "bugfix"
  },
  {
    "date": "2026-03-03",
    "event": "fix: ctax-partner-site copyAllScripts + avatar XSS + ad-maker MIME",
    "xp": 20,
    "type": "bugfix"
  },
  {
    "date": "2026-03-03",
    "event": "CTAX AI Tools Upgrade -- ICP context bridge, Save to Portal, Script Builder/Client Qualifier/Knowledge Base ICP injection, badge system",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: CTAX AI Tools Upgrade -- ICP-driven tool overhaul build #13",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Partner Portal Templates -- 6 landing page templates, template catalog, design specs, Supabase auth",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Partner Portal Templates -- build #12",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Marcom Engine V3 -- mission control, connection health, 7 integrations, engine locking, Inngest, approval queue",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Marcom Engine V3 -- marketing OS build #11",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Image Forge V3 -- Supabase auth, design sync, brand kits, asset library, analytics",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Image Forge V3 -- backend build #10",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Ad Intelligence V3 -- Supabase auth, competitor sync, briefs, alerts, analytics",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Ad Intelligence V3 -- backend build #9",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Pipeline Simulator V3 -- Supabase auth, cloud sync, simulation persistence, analytics",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Pipeline Simulator V3 -- backend build #8",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Uncommon Cents V3 -- Supabase auth, sync, saved calculations, analytics, dashboard",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Uncommon Cents V3 -- backend build #7",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "The Well V3 -- Supabase auth, cloud sync, community reflections, analytics, dashboard",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: The Well V3 -- backend build #6",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "DoodleForge V3 -- Supabase auth, credit system, Daily Guess game, share galleries, Doodie redesign",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: DoodleForge V3 -- Doodie redesign build #5",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "StockPilot V3 -- Supabase auth, Alpha Vantage market data, Claude AI thesis, Flight Plan, portfolio intelligence",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: StockPilot V3 -- greenfield backend build #4",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Occulus V3 -- CRM pipeline, scenario lab, stress test, rebalancer, AI reports, compliance logs",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Occulus V3 -- greenfield SaaS build #3",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Cash Cow V3 -- AI product discovery, Supabase auth, Claude research/ideation/briefs, cow branding",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Cash Cow V3 -- greenfield SaaS build #1",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Event Bus -- pub/sub router, Inngest delivery, dashboard, typed SDK",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Event Bus -- infrastructure package #2",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Auth + Billing Kit -- Supabase Auth, Stripe subs, tier gating, usage tracking, billing UI",
    "xp": 85,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Auth + Billing Kit -- infrastructure package #1",
    "xp": 35,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Deployed Image Forge to GitHub Pages (Pick & Shovel #5)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-03",
    "event": "Image Forge v1 -- canvas editor, 13 templates, brand kit, platform resize",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Image Forge -- Pick & Shovel Suite #5",
    "xp": 50,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Deployed Pipeline Simulator to GitHub Pages (Pick & Shovel #4)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-03",
    "event": "Pipeline Simulator v1 -- Kanban + Monte Carlo revenue simulation",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Pipeline Simulator -- Pick & Shovel Suite #4",
    "xp": 50,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Deployed Cash Cow to GitHub Pages (Pick & Shovel #3)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-03",
    "event": "Cash Cow v1 -- AI product idea generator, 15 niches, validation scoring",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-03",
    "event": "project: Cash Cow -- Pick & Shovel Suite #3",
    "xp": 50,
    "type": "project"
  },
  {
    "date": "2026-03-03",
    "event": "Plan: CTAX AI Tools Upgrade -- 6-phase ICP-driven overhaul, full audit + spec",
    "xp": 15,
    "type": "plan"
  },
  {
    "date": "2026-03-02",
    "event": "HoldingInsightCard 4-layer component + benchmark tape",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "Populated S&P/CFRA, StarMine, Congressional, Options blocks",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "Spacing fix below insight card",
    "xp": 20,
    "type": "bugfix"
  },
  {
    "date": "2026-03-02",
    "event": "Deployed StockPilot (insight cards + benchmark tape)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-02",
    "event": "Installed /face-lift skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-02",
    "event": "Plan: The Well Phase 7 -- Scripture Misuse",
    "xp": 15,
    "type": "plan"
  },
  {
    "date": "2026-03-02",
    "event": "Plan: Uncommon Cents Phase 7 -- Expansion Pack",
    "xp": 15,
    "type": "plan"
  },
  {
    "date": "2026-03-02",
    "event": "Deployed StockPilot (85 stocks + benchmarks)",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-02",
    "event": "StockPilot expansion -- 42 new stocks, 12 benchmarks",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "Subagent system -- 4 agents + routing rules",
    "xp": 25,
    "type": "config"
  },
  {
    "date": "2026-03-02",
    "event": "Plan: StockPilot Phase 6 roadmap",
    "xp": 15,
    "type": "plan"
  },
  {
    "date": "2026-03-02",
    "event": "UI/UX Pro Max search engine refactor",
    "xp": 25,
    "type": "refactor"
  },
  {
    "date": "2026-03-02",
    "event": "UI/UX Pro Max Tier 3+4 (7 CSVs)",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "UI/UX Pro Max Tier 2 adaptive style engine",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "UI/UX Pro Max Tier 1 core expansion (10 CSVs)",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "Skill library setup -- 6 SKILL.md files",
    "xp": 25,
    "type": "config"
  },
  {
    "date": "2026-03-02",
    "event": "Partner Portal super-skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-02",
    "event": "Compliance Wrapper super-skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-02",
    "event": "RAG Pipeline super-skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-02",
    "event": "/sync-hub skill + auto-sync system",
    "xp": 50,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "Database Schema super-skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-02",
    "event": "AI Tool Pipeline super-skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-02",
    "event": "Uncommon Cents content expansion -- 67 new concepts",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-02",
    "event": "Nightcrawler Max R4-6 -- 11 feat commits",
    "xp": 385,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "StockPilot v2 -- detail pages + 20 stocks",
    "xp": 70,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "The Well v2 -- word corrections + cards",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Uncommon Cents v2 -- calculators + concepts",
    "xp": 105,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "imagegen-mcp project setup",
    "xp": 50,
    "type": "project"
  },
  {
    "date": "2026-03-01",
    "event": "HeroSection React component",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Boho wave dividers + palette system",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Hero-section-system playbook",
    "xp": 25,
    "type": "playbook_created"
  },
  {
    "date": "2026-03-01",
    "event": "Page builder premium rebuild",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Client-facing copy rewrite",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "ICP Builder PDF footer",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "ICP Builder fixes (4 bugs)",
    "xp": 80,
    "type": "bugfix"
  },
  {
    "date": "2026-03-01",
    "event": "ICP Builder loader animation",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "ICP Builder PDF pagination rewrite",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "DoodleForge neumorphic polish",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "DoodleForge dark premium redesign",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Twinkling stars + shooting stars (CTAX)",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "AI scroll copy rewrite (CTAX)",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "DoodleForge build spec + EPIC mode",
    "xp": 15,
    "type": "docs"
  },
  {
    "date": "2026-03-01",
    "event": "The Well content expansion (9 words + 15 cards)",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Deployed The Well to Vercel",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-01",
    "event": "3D holo cards + contrast overhaul (CTAX)",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Portfolio link + copy URL",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Public project showcase page",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Immersive snap-scroll experience",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "DoodleForge pastel redesign + Wall of Shame",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "CSS scroll-snap sections",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Deployed DoodleForge to Vercel",
    "xp": 40,
    "type": "deployment"
  },
  {
    "date": "2026-03-01",
    "event": "Deployed 4 apps to Vercel",
    "xp": 160,
    "type": "deployment"
  },
  {
    "date": "2026-03-01",
    "event": "SVG pixel space invader",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Created ai-tooling-audit skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-01",
    "event": "Installed infinite-improver skill",
    "xp": 15,
    "type": "skill_created"
  },
  {
    "date": "2026-03-01",
    "event": "Cinematic scroll rewrite + dropdowns",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Created 55 growth/marketing skills",
    "xp": 825,
    "type": "skills_batch"
  },
  {
    "date": "2026-03-01",
    "event": "Plan: ICP cinematic scroll",
    "xp": 15,
    "type": "plan"
  },
  {
    "date": "2026-03-01",
    "event": "Portal dashboard with KPIs",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Pro subscription gating + paywall",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "ICP Builder immersive scroll",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Plan: ICP builder scroll",
    "xp": 15,
    "type": "plan"
  },
  {
    "date": "2026-03-01",
    "event": "Page builder publish flow",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Dark mode support",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Redesign 30-day challenge UX",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Lightbulb widget fix",
    "xp": 20,
    "type": "bugfix"
  },
  {
    "date": "2026-03-01",
    "event": "AEO pages implementation",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Rebuild business planner PDF",
    "xp": 35,
    "type": "feature"
  },
  {
    "date": "2026-03-01",
    "event": "Project setup: ctax-partner-site",
    "xp": 50,
    "type": "project"
  },
  {
    "date": "2026-03-01",
    "event": "Context optimization & plugin cleanup",
    "xp": 25,
    "type": "config"
  }
]
$seed$::jsonb) as e;
