-- tool_usage: per-session counter of which tools/skills/agents fired.
-- Powers the P6c Auto-Optimizations tab (find idle skills, overused tools, etc.).
create table public.tool_usage (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  project_slug text references public.projects(slug) on delete set null,
  tool_name text not null,
  category text,                    -- 'tool' | 'skill' | 'agent' | 'mcp'
  call_count int not null default 1,
  first_called_at timestamptz,
  last_called_at timestamptz,
  unique (session_id, tool_name)
);
create index tool_usage_name_idx on public.tool_usage (tool_name, last_called_at desc);
create index tool_usage_project_idx on public.tool_usage (project_slug, last_called_at desc);

alter table public.tool_usage enable row level security;

-- optimizations: findings from the auto-optimizer scanner (P6c).
create table public.optimizations (
  id bigint generated by default as identity primary key,
  kind text not null,               -- 'skill_unused' | 'skill_overlap' | 'agent_chain' | 'token_waste' | 'mcp_idle' | 'hook_cost'
  severity text not null default 'medium',  -- 'low' | 'medium' | 'high'
  title text not null,
  description text not null,
  target_ref text,                  -- e.g. skill name, agent name, mcp id
  suggested_action text,
  status text not null default 'open',  -- 'open' | 'dismissed' | 'applied'
  metadata jsonb,
  created_at timestamptz not null default now(),
  dismissed_at timestamptz,
  applied_at timestamptz
);
create index optimizations_status_idx on public.optimizations (status, severity, created_at desc);
create index optimizations_kind_idx on public.optimizations (kind, status);

alter table public.optimizations enable row level security;

-- ingester_state: track last scanned file and bookkeeping for the daemons.
create table public.ingester_state (
  id text primary key,              -- 'sessions' | 'optimizations' | 'vercel' | 'github'
  last_run_at timestamptz,
  last_file text,
  cursor jsonb,
  notes text
);

alter table public.ingester_state enable row level security;
