-- Self-hosted website analytics. Each project includes /track.js which POSTs
-- a pageview event to /api/track on the hub. The hub stores rows here, and
-- /website/analytics aggregates from this table.

create table public.pageviews (
  id bigint generated by default as identity primary key,
  site text not null,
  path text not null,
  referrer text,
  user_agent text,
  country text,
  device text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  session_id text,
  ts timestamptz not null default now()
);
create index pageviews_site_ts_idx on public.pageviews (site, ts desc);
create index pageviews_ts_idx on public.pageviews (ts desc);
create index pageviews_session_idx on public.pageviews (session_id, ts);

alter table public.pageviews enable row level security;