// Generated by Supabase MCP — `generate_typescript_types` for project rpejicodkvqocbgtasor.
// Regenerate with: mcp__supabase__generate_typescript_types(project_id).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      achievements: {
        Row: {
          category: string | null;
          current_value: number | null;
          derivation_query: string | null;
          description: string;
          id: string;
          name: string;
          target_value: number;
          unlocked_at: string | null;
        };
        Insert: {
          category?: string | null;
          current_value?: number | null;
          derivation_query?: string | null;
          description: string;
          id: string;
          name: string;
          target_value: number;
          unlocked_at?: string | null;
        };
        Update: {
          category?: string | null;
          current_value?: number | null;
          derivation_query?: string | null;
          description?: string;
          id?: string;
          name?: string;
          target_value?: number;
          unlocked_at?: string | null;
        };
        Relationships: [];
      };
      commits: {
        Row: {
          additions: number | null;
          author: string | null;
          committed_at: string;
          deletions: number | null;
          message: string | null;
          project_slug: string | null;
          sha: string;
          url: string | null;
        };
        Insert: {
          additions?: number | null;
          author?: string | null;
          committed_at: string;
          deletions?: number | null;
          message?: string | null;
          project_slug?: string | null;
          sha: string;
          url?: string | null;
        };
        Update: {
          additions?: number | null;
          author?: string | null;
          committed_at?: string;
          deletions?: number | null;
          message?: string | null;
          project_slug?: string | null;
          sha?: string;
          url?: string | null;
        };
        Relationships: [];
      };
      deployments: {
        Row: {
          branch: string | null;
          commit_sha: string | null;
          created_at: string;
          error_message: string | null;
          id: string;
          project_slug: string | null;
          ready_at: string | null;
          state: string | null;
          url: string | null;
          vercel_deployment_id: string | null;
        };
        Insert: {
          branch?: string | null;
          commit_sha?: string | null;
          created_at: string;
          error_message?: string | null;
          id?: string;
          project_slug?: string | null;
          ready_at?: string | null;
          state?: string | null;
          url?: string | null;
          vercel_deployment_id?: string | null;
        };
        Update: {
          branch?: string | null;
          commit_sha?: string | null;
          created_at?: string;
          error_message?: string | null;
          id?: string;
          project_slug?: string | null;
          ready_at?: string | null;
          state?: string | null;
          url?: string | null;
          vercel_deployment_id?: string | null;
        };
        Relationships: [];
      };
      ingester_state: {
        Row: {
          cursor: Json | null;
          id: string;
          last_file: string | null;
          last_run_at: string | null;
          notes: string | null;
        };
        Insert: {
          cursor?: Json | null;
          id: string;
          last_file?: string | null;
          last_run_at?: string | null;
          notes?: string | null;
        };
        Update: {
          cursor?: Json | null;
          id?: string;
          last_file?: string | null;
          last_run_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      integrations: {
        Row: {
          color: string | null;
          config: Json | null;
          description: string | null;
          icon: string | null;
          id: string;
          last_synced_at: string | null;
          name: string;
          status: string | null;
        };
        Insert: {
          color?: string | null;
          config?: Json | null;
          description?: string | null;
          icon?: string | null;
          id: string;
          last_synced_at?: string | null;
          name: string;
          status?: string | null;
        };
        Update: {
          color?: string | null;
          config?: Json | null;
          description?: string | null;
          icon?: string | null;
          id?: string;
          last_synced_at?: string | null;
          name?: string;
          status?: string | null;
        };
        Relationships: [];
      };
      message_excerpts: {
        Row: {
          content_preview: string | null;
          id: number;
          occurred_at: string | null;
          role: string;
          session_id: string;
          tool_name: string | null;
        };
        Insert: {
          content_preview?: string | null;
          id?: number;
          occurred_at?: string | null;
          role: string;
          session_id: string;
          tool_name?: string | null;
        };
        Update: {
          content_preview?: string | null;
          id?: number;
          occurred_at?: string | null;
          role?: string;
          session_id?: string;
          tool_name?: string | null;
        };
        Relationships: [];
      };
      optimizations: {
        Row: {
          applied_at: string | null;
          created_at: string;
          description: string;
          dismissed_at: string | null;
          id: number;
          kind: string;
          metadata: Json | null;
          severity: string;
          status: string;
          suggested_action: string | null;
          target_ref: string | null;
          title: string;
        };
        Insert: {
          applied_at?: string | null;
          created_at?: string;
          description: string;
          dismissed_at?: string | null;
          id?: number;
          kind: string;
          metadata?: Json | null;
          severity?: string;
          status?: string;
          suggested_action?: string | null;
          target_ref?: string | null;
          title: string;
        };
        Update: {
          applied_at?: string | null;
          created_at?: string;
          description?: string;
          dismissed_at?: string | null;
          id?: number;
          kind?: string;
          metadata?: Json | null;
          severity?: string;
          status?: string;
          suggested_action?: string | null;
          target_ref?: string | null;
          title?: string;
        };
        Relationships: [];
      };
      project_aliases: {
        Row: {
          alias: string;
          created_at: string;
          project_slug: string;
        };
        Insert: {
          alias: string;
          created_at?: string;
          project_slug: string;
        };
        Update: {
          alias?: string;
          created_at?: string;
          project_slug?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          badge: string | null;
          created_at: string;
          current_status: string | null;
          description: string | null;
          gradient: string | null;
          last_deploy_at: string | null;
          last_deploy_state: string | null;
          last_touched_at: string | null;
          live_url: string | null;
          mode: string | null;
          name: string;
          notes: string | null;
          repo_url: string | null;
          slug: string;
          soul: string | null;
          stack: string[] | null;
          tier: number | null;
          updated_at: string;
          vercel_project_id: string | null;
          vercel_url: string | null;
        };
        Insert: {
          badge?: string | null;
          created_at?: string;
          current_status?: string | null;
          description?: string | null;
          gradient?: string | null;
          last_deploy_at?: string | null;
          last_deploy_state?: string | null;
          last_touched_at?: string | null;
          live_url?: string | null;
          mode?: string | null;
          name: string;
          notes?: string | null;
          repo_url?: string | null;
          slug: string;
          soul?: string | null;
          stack?: string[] | null;
          tier?: number | null;
          updated_at?: string;
          vercel_project_id?: string | null;
          vercel_url?: string | null;
        };
        Update: {
          badge?: string | null;
          created_at?: string;
          current_status?: string | null;
          description?: string | null;
          gradient?: string | null;
          last_deploy_at?: string | null;
          last_deploy_state?: string | null;
          last_touched_at?: string | null;
          live_url?: string | null;
          mode?: string | null;
          name?: string;
          notes?: string | null;
          repo_url?: string | null;
          slug?: string;
          soul?: string | null;
          stack?: string[] | null;
          tier?: number | null;
          updated_at?: string;
          vercel_project_id?: string | null;
          vercel_url?: string | null;
        };
        Relationships: [];
      };
      sessions: {
        Row: {
          created_at: string;
          duration_min: number | null;
          ended_at: string | null;
          external_id: string | null;
          id: string;
          message_count: number;
          mode: string;
          model: string | null;
          project_slug: string | null;
          raw_path: string | null;
          started_at: string;
          summary: string | null;
          tokens_cache_read: number;
          tokens_cache_write: number;
          tokens_in: number;
          tokens_out: number;
          tool_calls: Json | null;
        };
        Insert: {
          created_at?: string;
          duration_min?: number | null;
          ended_at?: string | null;
          external_id?: string | null;
          id?: string;
          message_count?: number;
          mode: string;
          model?: string | null;
          project_slug?: string | null;
          raw_path?: string | null;
          started_at: string;
          summary?: string | null;
          tokens_cache_read?: number;
          tokens_cache_write?: number;
          tokens_in?: number;
          tokens_out?: number;
          tool_calls?: Json | null;
        };
        Update: {
          created_at?: string;
          duration_min?: number | null;
          ended_at?: string | null;
          external_id?: string | null;
          id?: string;
          message_count?: number;
          mode?: string;
          model?: string | null;
          project_slug?: string | null;
          raw_path?: string | null;
          started_at?: string;
          summary?: string | null;
          tokens_cache_read?: number;
          tokens_cache_write?: number;
          tokens_in?: number;
          tokens_out?: number;
          tool_calls?: Json | null;
        };
        Relationships: [];
      };
      tasks: {
        Row: {
          completed_at: string | null;
          due: string | null;
          id: string;
          project_slug: string | null;
          status: string | null;
          synced_at: string;
          title: string;
          url: string | null;
        };
        Insert: {
          completed_at?: string | null;
          due?: string | null;
          id: string;
          project_slug?: string | null;
          status?: string | null;
          synced_at?: string;
          title: string;
          url?: string | null;
        };
        Update: {
          completed_at?: string | null;
          due?: string | null;
          id?: string;
          project_slug?: string | null;
          status?: string | null;
          synced_at?: string;
          title?: string;
          url?: string | null;
        };
        Relationships: [];
      };
      tool_usage: {
        Row: {
          call_count: number;
          category: string | null;
          first_called_at: string | null;
          id: number;
          last_called_at: string | null;
          project_slug: string | null;
          session_id: string;
          tool_name: string;
        };
        Insert: {
          call_count?: number;
          category?: string | null;
          first_called_at?: string | null;
          id?: number;
          last_called_at?: string | null;
          project_slug?: string | null;
          session_id: string;
          tool_name: string;
        };
        Update: {
          call_count?: number;
          category?: string | null;
          first_called_at?: string | null;
          id?: number;
          last_called_at?: string | null;
          project_slug?: string | null;
          session_id?: string;
          tool_name?: string;
        };
        Relationships: [];
      };
      xp_events: {
        Row: {
          event: string;
          id: number;
          occurred_at: string;
          project_slug: string | null;
          source: string | null;
          type: string;
          xp: number;
        };
        Insert: {
          event: string;
          id?: number;
          occurred_at: string;
          project_slug?: string | null;
          source?: string | null;
          type: string;
          xp: number;
        };
        Update: {
          event?: string;
          id?: number;
          occurred_at?: string;
          project_slug?: string | null;
          source?: string | null;
          type?: string;
          xp?: number;
        };
        Relationships: [];
      };
    };
    Views: {
      activity_feed: {
        Row: {
          detail: string | null;
          kind: string | null;
          meta: Json | null;
          occurred_at: string | null;
          project_slug: string | null;
        };
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
