// Generated by Supabase MCP — `generate_typescript_types` for project rpejicodkvqocbgtasor.
// Regenerate with: mcp__supabase__generate_typescript_types(project_id).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type Row = Record<string, unknown>;

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      achievements: {
        Row: {
          category: string | null;
          current_value: number | null;
          derivation_query: string | null;
          description: string;
          id: string;
          name: string;
          target_value: number;
          unlocked_at: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["achievements"]["Row"]> & {
          description: string;
          id: string;
          name: string;
          target_value: number;
        };
        Update: Partial<Database["public"]["Tables"]["achievements"]["Row"]>;
        Relationships: [];
      };
      commits: {
        Row: {
          additions: number | null;
          author: string | null;
          committed_at: string;
          deletions: number | null;
          message: string | null;
          project_slug: string | null;
          sha: string;
          url: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["commits"]["Row"]> & {
          committed_at: string;
          sha: string;
        };
        Update: Partial<Database["public"]["Tables"]["commits"]["Row"]>;
        Relationships: [];
      };
      deployments: {
        Row: {
          branch: string | null;
          commit_sha: string | null;
          created_at: string;
          error_message: string | null;
          id: string;
          project_slug: string | null;
          ready_at: string | null;
          state: string | null;
          url: string | null;
          vercel_deployment_id: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["deployments"]["Row"]> & {
          created_at: string;
        };
        Update: Partial<Database["public"]["Tables"]["deployments"]["Row"]>;
        Relationships: [];
      };
      inbox_emails: {
        Row: {
          id: string;
          fastmail_id: string;
          thread_id: string | null;
          from_address: string;
          from_name: string | null;
          to_address: string | null;
          subject: string | null;
          body_preview: string | null;
          body_full: string | null;
          received_at: string | null;
          category: string | null;
          category_confidence: number | null;
          category_reasoning: string | null;
          action_taken: string | null;
          draft_response: string | null;
          fastmail_draft_id: string | null;
          draft_status: string;
          sent_at: string | null;
          discarded_at: string | null;
          send_error: string | null;
          classified_at: string | null;
          drafted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["inbox_emails"]["Row"]> & {
          fastmail_id: string;
          from_address: string;
        };
        Update: Partial<Database["public"]["Tables"]["inbox_emails"]["Row"]>;
        Relationships: [];
      };
      ingester_state: {
        Row: {
          cursor: Json | null;
          id: string;
          last_file: string | null;
          last_run_at: string | null;
          notes: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["ingester_state"]["Row"]> & {
          id: string;
        };
        Update: Partial<Database["public"]["Tables"]["ingester_state"]["Row"]>;
        Relationships: [];
      };
      integrations: {
        Row: {
          color: string | null;
          config: Json | null;
          description: string | null;
          icon: string | null;
          id: string;
          last_synced_at: string | null;
          name: string;
          status: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["integrations"]["Row"]> & {
          id: string;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["integrations"]["Row"]>;
        Relationships: [];
      };
      leads: {
        Row: {
          closed_at: string | null;
          company: string | null;
          contacted_at: string | null;
          created_at: string;
          email: string | null;
          external_id: string | null;
          id: string;
          message: string | null;
          metadata: Json | null;
          name: string | null;
          need: string | null;
          notes: string | null;
          qualified_at: string | null;
          raw_body: string | null;
          raw_subject: string | null;
          received_at: string;
          source: string;
          source_url: string | null;
          status: string;
          updated_at: string;
          utm_campaign: string | null;
          utm_medium: string | null;
          utm_source: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["leads"]["Row"]> & {
          received_at: string;
          source: string;
        };
        Update: Partial<Database["public"]["Tables"]["leads"]["Row"]>;
        Relationships: [];
      };
      message_excerpts: {
        Row: {
          content_preview: string | null;
          id: number;
          occurred_at: string | null;
          role: string;
          session_id: string;
          tool_name: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["message_excerpts"]["Row"]> & {
          role: string;
          session_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["message_excerpts"]["Row"]>;
        Relationships: [];
      };
      pageviews: {
        Row: {
          id: number;
          site: string;
          path: string;
          referrer: string | null;
          user_agent: string | null;
          country: string | null;
          device: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          session_id: string | null;
          ts: string;
        };
        Insert: Partial<Database["public"]["Tables"]["pageviews"]["Row"]> & {
          site: string;
          path: string;
        };
        Update: Partial<Database["public"]["Tables"]["pageviews"]["Row"]>;
        Relationships: [];
      };
      optimizations: {
        Row: {
          applied_at: string | null;
          created_at: string;
          description: string;
          dismissed_at: string | null;
          id: number;
          kind: string;
          metadata: Json | null;
          severity: string;
          status: string;
          suggested_action: string | null;
          target_ref: string | null;
          title: string;
        };
        Insert: Partial<Database["public"]["Tables"]["optimizations"]["Row"]> & {
          description: string;
          kind: string;
          title: string;
        };
        Update: Partial<Database["public"]["Tables"]["optimizations"]["Row"]>;
        Relationships: [];
      };
      project_aliases: {
        Row: {
          alias: string;
          created_at: string;
          project_slug: string;
        };
        Insert: Partial<Database["public"]["Tables"]["project_aliases"]["Row"]> & {
          alias: string;
          project_slug: string;
        };
        Update: Partial<Database["public"]["Tables"]["project_aliases"]["Row"]>;
        Relationships: [];
      };
      projects: {
        Row: {
          badge: string | null;
          created_at: string;
          current_status: string | null;
          description: string | null;
          gradient: string | null;
          last_deploy_at: string | null;
          last_deploy_state: string | null;
          last_touched_at: string | null;
          live_url: string | null;
          mode: string | null;
          name: string;
          notes: string | null;
          repo_url: string | null;
          slug: string;
          soul: string | null;
          stack: string[] | null;
          tier: number | null;
          updated_at: string;
          vercel_project_id: string | null;
          vercel_url: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["projects"]["Row"]> & {
          name: string;
          slug: string;
        };
        Update: Partial<Database["public"]["Tables"]["projects"]["Row"]>;
        Relationships: [];
      };
      sessions: {
        Row: {
          created_at: string;
          duration_min: number | null;
          ended_at: string | null;
          external_id: string | null;
          id: string;
          message_count: number;
          mode: string;
          model: string | null;
          project_slug: string | null;
          raw_path: string | null;
          started_at: string;
          summary: string | null;
          tokens_cache_read: number;
          tokens_cache_write: number;
          tokens_in: number;
          tokens_out: number;
          tool_calls: Json | null;
        };
        Insert: Partial<Database["public"]["Tables"]["sessions"]["Row"]> & {
          mode: string;
          started_at: string;
        };
        Update: Partial<Database["public"]["Tables"]["sessions"]["Row"]>;
        Relationships: [];
      };
      tasks: {
        Row: {
          completed_at: string | null;
          due: string | null;
          id: string;
          project_slug: string | null;
          status: string | null;
          synced_at: string;
          title: string;
          url: string | null;
        };
        Insert: Partial<Database["public"]["Tables"]["tasks"]["Row"]> & {
          id: string;
          title: string;
        };
        Update: Partial<Database["public"]["Tables"]["tasks"]["Row"]>;
        Relationships: [];
      };
      tool_usage: {
        Row: {
          call_count: number;
          category: string | null;
          first_called_at: string | null;
          id: number;
          last_called_at: string | null;
          project_slug: string | null;
          session_id: string;
          tool_name: string;
        };
        Insert: Partial<Database["public"]["Tables"]["tool_usage"]["Row"]> & {
          session_id: string;
          tool_name: string;
        };
        Update: Partial<Database["public"]["Tables"]["tool_usage"]["Row"]>;
        Relationships: [];
      };
      xp_events: {
        Row: {
          event: string;
          id: number;
          occurred_at: string;
          project_slug: string | null;
          source: string | null;
          type: string;
          xp: number;
        };
        Insert: Partial<Database["public"]["Tables"]["xp_events"]["Row"]> & {
          event: string;
          occurred_at: string;
          type: string;
          xp: number;
        };
        Update: Partial<Database["public"]["Tables"]["xp_events"]["Row"]>;
        Relationships: [];
      };
    };
    Views: {
      activity_feed: {
        Row: {
          detail: string | null;
          kind: string | null;
          meta: Json | null;
          occurred_at: string | null;
          project_slug: string | null;
        };
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
